// This file is auto-generated by @hey-api/openapi-ts

export type ApiHealthData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/api/v1/health/';
};

export type ApiHealthResponses = {
	/**
	 * Successful Response
	 */
	200: unknown;
};

export type ClientOptions = {
	baseUrl: 'http://www.docker.localhost' | (string & {});
};
