---
- name: Download task
  ansible.builtin.get_url:
    checksum: "{{ task_checksum }}"
    url: "{{ task_url }}"
    dest: "{{ playbook_dir }}/../dest/task.tar.gz"
    mode: 775
- name: Untar task
  ansible.builtin.unarchive:
    remote_src: true
    src: "{{ playbook_dir }}/../dest/task.tar.gz"
    dest: "{{ playbook_dir }}/../dest"
    mode: 775
    owner: "{{ ansible_user_id }}"
